using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Flock.Editor.Catalog
{
    /// Read-only inspector for the generated FlockContentCatalog. Renders shops, configs and templates
    /// as collapsible cards so non-programmers can browse backend content in Unity without reading C#.
    [CustomEditor(typeof(FlockContentCatalog))]
    public class FlockContentCatalogInspector : UnityEditor.Editor
    {
        private bool _shopsOpen = true;
        private bool _configsOpen = true;
        private bool _templatesOpen = true;
        private bool _achievementsOpen = true;

        private GUIStyle _title;
        private GUIStyle _section;
        private GUIStyle _card;

        public override void OnInspectorGUI()
        {
            EnsureStyles();
            FlockContentCatalog catalog = (FlockContentCatalog)target;

            EditorGUILayout.Space(4);
            GUILayout.Label("Flock Content Catalog", _title);
            EditorGUILayout.LabelField("Game Version", Dash(catalog.gameVersion));
            EditorGUILayout.LabelField("Version ID", Dash(catalog.gameVersionId));
            EditorGUILayout.LabelField("Generated (UTC)", Dash(catalog.generatedAtUtc));
            EditorGUILayout.HelpBox(
                "Read-only. Generated by Flock Codegen and overwritten on every Sync. Edit content on the Flock dashboard.",
                MessageType.Info);

            _shopsOpen = DrawSectionHeader($"Shops ({catalog.shops.Count})", _shopsOpen);
            if (_shopsOpen) DrawShops(catalog.shops);

            _configsOpen = DrawSectionHeader($"Game Configs ({catalog.configs.Count})", _configsOpen);
            if (_configsOpen) DrawSchemas(catalog.configs);

            _templatesOpen = DrawSectionHeader($"Player Templates ({catalog.templates.Count})", _templatesOpen);
            if (_templatesOpen) DrawSchemas(catalog.templates);

            _achievementsOpen = DrawSectionHeader($"Achievements ({catalog.achievements.Count})", _achievementsOpen);
            if (_achievementsOpen) DrawAchievements(catalog.achievements);
        }

        private void DrawAchievements(List<CatalogAchievement> achievements)
        {
            if (achievements.Count == 0) { EmptyNote("No achievements."); return; }
            EditorGUILayout.BeginVertical(_card);
            foreach (CatalogAchievement achievement in achievements)
            {
                string label = string.IsNullOrEmpty(achievement.type) ? achievement.name : $"{achievement.name}  ({achievement.type})";
                EditorGUILayout.LabelField(label);
            }
            EditorGUILayout.EndVertical();
        }

        private void DrawShops(List<CatalogShop> shops)
        {
            if (shops.Count == 0) { EmptyNote("No shops."); return; }
            foreach (CatalogShop shop in shops)
            {
                EditorGUILayout.BeginVertical(_card);
                GUILayout.Label(HeaderWithTag(shop.name, shop.status), _section);
                if (shop.items.Count == 0) EmptyNote("No items.");
                foreach (CatalogShopItem item in shop.items)
                {
                    string price = item.price > 0 ? $"{item.price} {item.currency}".Trim() : "free";
                    EditorGUILayout.LabelField(item.name, price);
                }
                EditorGUILayout.EndVertical();
            }
        }

        private void DrawSchemas(List<CatalogSchema> schemas)
        {
            if (schemas.Count == 0) { EmptyNote("Nothing generated."); return; }
            foreach (CatalogSchema schema in schemas)
            {
                EditorGUILayout.BeginVertical(_card);
                GUILayout.Label(HeaderWithTag(schema.name, schema.tag), _section);
                if (schema.fields.Count == 0) EmptyNote("No fields.");
                foreach (CatalogField field in schema.fields)
                {
                    string label = string.IsNullOrEmpty(field.type) ? field.name : $"{field.name}  ({field.type})";
                    EditorGUILayout.LabelField(label, Dash(field.value));
                }
                EditorGUILayout.EndVertical();
            }
        }

        private static string HeaderWithTag(string name, string tag)
            => string.IsNullOrEmpty(tag) ? name : $"{name}   [{tag}]";

        private static string Dash(string value) => string.IsNullOrEmpty(value) ? "—" : value;

        private bool DrawSectionHeader(string label, bool open)
        {
            EditorGUILayout.Space(6);
            return EditorGUILayout.Foldout(open, label, true, EditorStyles.foldoutHeader);
        }

        private static void EmptyNote(string text) => EditorGUILayout.LabelField(text, EditorStyles.miniLabel);

        private void EnsureStyles()
        {
            if (_title != null) return;
            _title = new GUIStyle(EditorStyles.boldLabel) { fontSize = 15 };
            _section = new GUIStyle(EditorStyles.boldLabel) { fontSize = 12 };
            _card = new GUIStyle(EditorStyles.helpBox)
            {
                padding = new RectOffset(10, 10, 8, 8),
                margin = new RectOffset(0, 0, 2, 4)
            };
        }
    }
}
