using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    // Emits the FlockAchievementId enum, a JsonConverter that maps it to/from the raw achievement_name, and an
    // enum-keyed UnlockAchievementAsync extension. Achievements are the schema fields of the single player
    // template tagged "achievement"; each enum member maps to its raw field name (the achievement_name the
    // backend expects). The converter is the single source of the enum<->string mapping — the unlock extension
    // and the generated achievement-detail config both use it.
    internal static class AchievementEmitter
    {
        private const string AchievementTag = "achievement";

        private sealed class AchievementEntry
        {
            public string Member;
            public string Name;
        }

        public static int Emit(IList<PlayerTemplateSchema> playerTemplates, string outputDir)
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
            Directory.CreateDirectory(outputDir);

            // Tags are unique per the provider contract, so the first match is the achievements template.
            PlayerTemplateSchema template = (playerTemplates ?? new List<PlayerTemplateSchema>())
                .FirstOrDefault(t => t != null && string.Equals(t.Tag, AchievementTag, StringComparison.OrdinalIgnoreCase));

            if (template == null)
            {
                Debug.Log("[Flock Codegen] Achievements: no player template tagged \"achievement\" — nothing to emit.");
                return 0;
            }

            HashSet<string> members = new HashSet<string>();
            List<AchievementEntry> entries = new List<AchievementEntry>();
            foreach (TypedSchema field in (template.Schema ?? new List<TypedSchema>())
                .Where(f => f != null && !string.IsNullOrEmpty(f.FieldName)))
            {
                entries.Add(new AchievementEntry
                {
                    Member = CodeGenNamingHelpers.UnDuplicate(CodeGenNamingHelpers.ToPascalCase(field.FieldName), members),
                    Name = field.FieldName
                });
            }

            if (entries.Count == 0)
            {
                Debug.LogWarning($"[Flock Codegen] Achievements: template '{template.Name}' is tagged \"achievement\" but has no fields — nothing to emit.");
                return 0;
            }

            File.WriteAllText(Path.Combine(outputDir, "FlockAchievements.g.cs"), BuildSource(entries));
            Debug.Log($"[Flock Codegen] Achievements: emitted {entries.Count} achievement id(s) from '{template.Name}'.");
            return entries.Count;
        }

        private static string BuildSource(List<AchievementEntry> entries)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            // The enum + converter compile alone; only the unlock extension needs the player/command types,
            // so guard those usings to avoid unused-using warnings when the player provider is stripped.
            sb.AppendLine("using System;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine("#if !FLOCK_NO_PLAYER");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine("using Flock.Providers;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Achievements");
            sb.AppendLine("{");

            // Enum
            sb.AppendLine("    public enum FlockAchievementId");
            sb.AppendLine("    {");
            foreach (AchievementEntry entry in entries)
            {
                sb.AppendLine($"        /// <summary>{CodeGenNamingHelpers.SanitizeForLineComment(entry.Name)}</summary>");
                sb.AppendLine($"        {entry.Member},");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // Converter — the single source of the enum<->achievement_name mapping.
            sb.AppendLine("    public sealed class FlockAchievementIdConverter : JsonConverter");
            sb.AppendLine("    {");
            sb.AppendLine("        public override bool CanConvert(Type objectType) => objectType == typeof(FlockAchievementId);");
            sb.AppendLine();
            sb.AppendLine("        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)");
            sb.AppendLine("            => writer.WriteValue(ToName((FlockAchievementId)value));");
            sb.AppendLine();
            sb.AppendLine("        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)");
            sb.AppendLine("            => FromName(reader.Value as string);");
            sb.AppendLine();
            sb.AppendLine("        public static string ToName(FlockAchievementId achievement)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (achievement)");
            sb.AppendLine("            {");
            foreach (AchievementEntry entry in entries)
                sb.AppendLine($"                case FlockAchievementId.{entry.Member}: return \"{CodeGenNamingHelpers.EscapeStringLiteral(entry.Name)}\";");
            sb.AppendLine("                default: throw new ArgumentOutOfRangeException(nameof(achievement));");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static FlockAchievementId FromName(string name)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (name)");
            sb.AppendLine("            {");
            foreach (AchievementEntry entry in entries)
                sb.AppendLine($"                case \"{CodeGenNamingHelpers.EscapeStringLiteral(entry.Name)}\": return FlockAchievementId.{entry.Member};");
            sb.AppendLine("                default: throw new JsonSerializationException($\"Unknown achievement name '{name}'. Re-run Flock Codegen if the backend added achievements.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Unlock extension (player-provider only).
            sb.AppendLine("    public static class FlockAchievementExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("#if !FLOCK_NO_PLAYER");
            sb.AppendLine("        public static Task<PlayerData> UnlockAchievementAsync(this FlockCommandProvider commands, FlockAchievementId achievement, CancellationToken cancellationToken = default)");
            sb.AppendLine("            => commands.UnlockAchievementAsync(FlockAchievementIdConverter.ToName(achievement), cancellationToken);");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
