using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class CommandAccessorEmitter
    {
        public static int Emit(
            IList<PlayerTemplateSchema> playerTemplates,
            IReadOnlyDictionary<string, string> templateClassNamesById,
            string outputDir)
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
            Directory.CreateDirectory(outputDir);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Templates");
            sb.AppendLine("{");

            int methodCount = 0;

            IEnumerable<PlayerTemplateSchema> ordered =
                (playerTemplates ?? new List<PlayerTemplateSchema>())
                    .OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                    .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal);

            foreach (PlayerTemplateSchema t in ordered)
            {
                if (t == null || string.IsNullOrEmpty(t.Id)) continue;
                if (!templateClassNamesById.TryGetValue(t.Id, out string className)) continue;

                EmitUpdateMethod(sb, className);
                methodCount++;
            }

            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "FlockTemplateCommands.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Command accessors: emitted {methodCount}.");
            return methodCount;
        }

        private static void EmitUpdateMethod(StringBuilder sb, string className)
        {
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Send the updated {className} to the server.");
            sb.AppendLine("        /// Mutate the populated fields, then call this on the object.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public Task<PlayerData> UpdateAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (string.IsNullOrEmpty(PlayerDataId)) throw new InvalidOperationException(\"PlayerDataId is not set on {className}; fetch via the matching Get accessor first.\");");
            sb.AppendLine($"            List<DataField> fields = {className}.Schema.ToDataFieldList(this);");
            sb.AppendLine("            return FlockClient.Instance.Commands.UpdatePlayerDataAsync(PlayerDataId, fields, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }
}
