using System;
using System.Threading.Tasks;
using Flock.Config;
using UnityEditor;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    /// <summary>
    /// Headless entry points for CI. Invoke via Unity's command line, e.g.
    /// <c>Unity -batchmode -projectPath . -executeMethod Flock.Editor.Codegen.FlockCodegenCli.Verify -logFile -</c>.
    /// Do NOT pass <c>-quit</c>: each method runs async then exits the editor itself with a status code.
    /// </summary>
    public static class FlockCodegenCli
    {
        private const int ExitOk = 0;       // success / no drift
        private const int ExitError = 1;    // could not run (bad config, fetch failure, crash)
        private const int ExitDrift = 2;    // committed generated code is stale vs the backend schema

        /// <summary>CI: regenerate typed accessors from the backend schema, then exit.</summary>
        public static void Sync() => RunThenExit(SyncAsync());

        /// <summary>CI: exit non-zero when the committed generated code is stale vs the backend schema. Writes nothing.</summary>
        public static void Verify() => RunThenExit(VerifyAsync());

        private static async Task<int> SyncAsync()
        {
            if (!FlockCodegenMenu.TryLoadConfig(out FlockConfigAsset config, out string error))
            {
                Debug.LogError($"[Flock Codegen] {error}");
                return ExitError;
            }
            if (!FlockCodegenMenu.TryResolveGeneratedPath(config.generatedCodePath, out string generatedRoot, out string pathError))
            {
                Debug.LogError($"[Flock Codegen] {pathError}");
                return ExitError;
            }

            try
            {
                await FlockCodegenMenu.RunCodegenAsync(config, generatedRoot);
                Debug.Log("[Flock Codegen] CI sync complete.");
                return ExitOk;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Flock Codegen] CI sync failed: {ex.GetType().Name}: {ex.Message}");
                return ExitError;
            }
        }

        private static async Task<int> VerifyAsync()
        {
            if (!FlockCodegenMenu.TryLoadConfig(out FlockConfigAsset config, out string error))
            {
                Debug.LogError($"[Flock Codegen] {error}");
                return ExitError;
            }

            FlockSchemaSnapshot snapshot;
            try
            {
                snapshot = await SchemaFetcher.FetchAsync(config);
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Flock Codegen] Verify could not fetch the backend schema: {ex.GetType().Name}: {ex.Message}");
                return ExitError;
            }

            string generatedId = FlockCodeGenValidator.GetGeneratedGameVersionId();
            if (string.IsNullOrEmpty(generatedId))
            {
                Debug.LogError("[Flock Codegen] Drift: no generated SchemasManifest is compiled in. Run Sync and commit the generated code.");
                return ExitDrift;
            }
            if (!string.Equals(generatedId, snapshot.GameVersionId, StringComparison.Ordinal))
            {
                Debug.LogError(
                    $"[Flock Codegen] Drift: committed schemas are for game_version_id='{generatedId}' but the backend now " +
                    $"reports '{snapshot.GameVersionId}'. Re-run Sync and commit the regenerated code.");
                return ExitDrift;
            }

            string generatedHash = FlockCodeGenValidator.GetGeneratedContentHash();
            string currentHash = SchemaHasher.ComputeContentHash(snapshot);
            if (string.IsNullOrEmpty(generatedHash))
            {
                Debug.LogError(
                    "[Flock Codegen] Drift: the committed SchemasManifest has no ContentHash (generated by an older SDK). " +
                    "Re-run Sync and commit so content drift can be verified.");
                return ExitDrift;
            }
            if (!string.Equals(generatedHash, currentHash, StringComparison.Ordinal))
            {
                Debug.LogError(
                    "[Flock Codegen] Drift: the backend schema content changed within the same game version " +
                    "(fields, types, or tags) since the committed code was generated. Re-run Sync and commit.");
                return ExitDrift;
            }

            Debug.Log($"[Flock Codegen] Verify OK — generated schemas match backend game_version_id='{snapshot.GameVersionId}' (content hash matches).");
            return ExitOk;
        }

        // Drives the async work to completion, then exits the editor with the status code in batch mode.
        // Async (not a blocking .Result) so the continuation can run on Unity's main-thread context
        // without deadlocking; the finally guarantees CI never hangs waiting on a forgotten exit.
        private static async void RunThenExit(Task<int> work)
        {
            int code = ExitError;
            try
            {
                code = await work;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Flock Codegen] CLI crashed: {ex.GetType().Name}: {ex.Message}\n{ex.StackTrace}");
                code = ExitError;
            }
            finally
            {
                if (Application.isBatchMode)
                    EditorApplication.Exit(code);
                else
                    Debug.Log($"[Flock Codegen] CLI finished with exit code {code} (interactive editor left open).");
            }
        }
    }
}
