using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    /// <summary>Emits the generated <c>SchemasManifest</c> — GameVersionId plus a content hash that the build guard and CI Verify compare against to detect drift.</summary>
    internal static class ManifestEmitter
    {
        public static void Emit(FlockSchemaSnapshot snapshot, string outputDir, int achievementCount)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            string contentHash = SchemaHasher.ComputeContentHash(snapshot);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Flock.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SchemasManifest");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string GameVersionId = \"{CodeGenNamingHelpers.EscapeStringLiteral(snapshot.GameVersionId)}\";");
            sb.AppendLine($"        public const string ContentHash = \"{contentHash}\";");
            sb.AppendLine($"        public const string GeneratedAtUtc = \"{snapshot.FetchedAt.ToString("o", CultureInfo.InvariantCulture)}\";");
            sb.AppendLine($"        public const int PlayerTemplateCount = {snapshot.PlayerTemplates.Count};");
            sb.AppendLine($"        public const int GameConfigCount = {snapshot.GameConfigs.Count};");
            sb.AppendLine($"        public const int ShopCount = {snapshot.Shops.Count};");
            sb.AppendLine($"        public const int AchievementCount = {achievementCount};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "SchemasManifest.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Manifest written for game_version_id={snapshot.GameVersionId}.");
        }
    }
}
