using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class PlayerTemplateEmitter
    {
        public static EmitResult Emit(IList<PlayerTemplateSchema> templates, string outputDir)
        {
            ResetDirectory(outputDir);

            HashSet<string> used = new HashSet<string>();
            Dictionary<string, string> classNamesById = new Dictionary<string, string>();
            int emitted = 0, skipped = 0;

            foreach (PlayerTemplateSchema t in templates.OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                                                          .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal))
            {
                if (t.Schema == null || t.Schema.Count == 0)
                {
                    Debug.LogWarning($"[Flock Codegen] PlayerTemplate '{t.Name}' (id={t.Id}) has no schema; skipping.");
                    skipped++;
                    continue;
                }

                string className = CodeGenNamingHelpers.UnDuplicate(CodeGenNamingHelpers.ToPascalCase(t.Name) + "Template", used);
                string source = BuildClass(className, t, used);
                File.WriteAllText(Path.Combine(outputDir, className + ".g.cs"), source);
                if (!string.IsNullOrEmpty(t.Id))
                    classNamesById[t.Id] = className;
                emitted++;
            }

            Debug.Log($"[Flock Codegen] PlayerTemplates: emitted {emitted}, skipped {skipped}.");
            return new EmitResult(emitted, classNamesById);
        }

        public readonly struct EmitResult
        {
            public readonly int Count;
            public readonly IReadOnlyDictionary<string, string> ClassNamesById;
            public EmitResult(int count, IReadOnlyDictionary<string, string> classNamesById)
            {
                Count = count;
                ClassNamesById = classNamesById;
            }
        }

        private static string BuildClass(string className, PlayerTemplateSchema t, HashSet<string> usedClassNames)
        {
            List<string> reservedProps = new List<string> { className, "SourceId", "SourceName", "PlayerDataId", "Schema" };

            StringBuilder schemaSource = new StringBuilder();
            schemaSource.AppendLine($"        public const string SourceId = \"{CodeGenNamingHelpers.EscapeStringLiteral(t.Id)}\";");
            schemaSource.AppendLine($"        public const string SourceName = \"{CodeGenNamingHelpers.EscapeStringLiteral(t.Name)}\";");
            schemaSource.AppendLine("        [JsonIgnore] public string PlayerDataId { get; set; }");
            List<string> nestedClasses = new List<string>();
            int emittedProps = SchemaPropertyEmitter.EmitProperties(
                t.Schema, className, "{ get; set; }",
                schemaSource, nestedClasses, usedClassNames, reservedProps, className);
            if (emittedProps == 0)
            {
                Debug.LogWarning($"[Flock Codegen] {className}: schema had {t.Schema.Count} field(s) but none were emittable.");
            }
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine($"//   Source: PlayerTemplate id={CodeGenNamingHelpers.SanitizeForLineComment(t.Id)} name={CodeGenNamingHelpers.SanitizeForLineComment(t.Name)}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine("using Newtonsoft.Json.Linq;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Templates");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.Append(schemaSource);
            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<TypedSchema> Schema { get; } = new List<TypedSchema>");
            sb.AppendLine("        {");
            for (int i = 0; i < t.Schema.Count; i++)
            {
                sb.Append("            ");
                sb.Append(SerializeTypedSchema(t.Schema[i], "            "));
                if (i < t.Schema.Count - 1) sb.AppendLine(",");
                else sb.AppendLine();
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            foreach (string nested in nestedClasses)
            {
                sb.AppendLine();
                sb.Append(nested);
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string SerializeTypedSchema(TypedSchema field, string baseIndent)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("new TypedSchema { ");
            sb.Append($"Type = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.Type ?? "")}\", ");
            sb.Append($"FieldName = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.FieldName ?? "")}\", ");
            sb.Append($"TypeName = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.TypeName ?? "")}\"");

            if (field.Schema is List<TypedSchema> list && list.Count > 0)
            {
                sb.Append(", Schema = new List<TypedSchema>");
                sb.AppendLine();
                sb.Append(baseIndent);
                sb.AppendLine("{");
                string innerIndent = baseIndent + "    ";
                for (int i = 0; i < list.Count; i++)
                {
                    sb.Append(innerIndent);
                    sb.Append(SerializeTypedSchema(list[i], innerIndent));
                    if (i < list.Count - 1) sb.AppendLine(",");
                    else sb.AppendLine();
                }
                sb.Append(baseIndent);
                sb.Append("}");
            }
            else if (field.Schema is TypedSchema single)
            {
                sb.Append(", Schema = ");
                sb.Append(SerializeTypedSchema(single, baseIndent));
            }

            sb.Append(" }");
            return sb.ToString();
        }

        private static void ResetDirectory(string dir)
        {
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
            Directory.CreateDirectory(dir);
        }
    }
}
