using System.Collections.Generic;
using System.IO;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    // Must run after PlayerTemplateEmitter — that emitter wipes the output directory.
    internal static class PlayerAccessorEmitter
    {
        public static int Emit(
            IList<PlayerTemplateSchema> playerTemplates,
            IReadOnlyDictionary<string, string> templateClassNamesById,
            string outputDir)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine("using Flock.Providers;");
            sb.AppendLine("using Newtonsoft.Json.Linq;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Templates");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FlockPlayerProviderExtensions");
            sb.AppendLine("    {");

            int methodCount = 0;
            var usedMethodNames = new HashSet<string>();

            foreach (var t in playerTemplates ?? new List<PlayerTemplateSchema>())
            {
                if (t == null || string.IsNullOrEmpty(t.Id) || string.IsNullOrEmpty(t.Name)) continue;
                if (!templateClassNamesById.TryGetValue(t.Id, out string className)) continue;

                EmitReadMethod(sb, className, t.Name, usedMethodNames);
                methodCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "FlockPlayerProviderExtensions.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Player accessors: emitted {methodCount}.");
            return methodCount;
        }

        private static void EmitReadMethod(StringBuilder sb, string className, string sourceName, HashSet<string> usedMethodNames)
        {
            string methodName = CodeGenNamingHelpers.UnDuplicate("Get" + CodeGenNamingHelpers.ToPascalCase(sourceName) + "Async", usedMethodNames);

            sb.AppendLine($"        public static async Task<{className}> {methodName}(");
            sb.AppendLine($"            this PlayerProvider provider,");
            sb.AppendLine($"            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            PlayerData pd = await provider.GetMyDataByTemplateAsync({className}.SourceId, cancellationToken);");
            sb.AppendLine("            if (pd == null || pd.Data == null) return null;");
            sb.AppendLine($"            {className} result = pd.Data.ToFlatObject().ToObject<{className}>();");
            sb.AppendLine("            result.PlayerDataId = pd.Id;");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
